#ifndef ETH_CSR_H
#define ETH_CSR_H
#include "stdint.h"
#define ETH_CSR_ETH_MAC_LOW_BIT_WIDTH 24
#define ETH_CSR_ETH_MAC_LOW_BIT_MASK 0xffffff
#define ETH_CSR_ETH_MAC_LOW_BIT_OFFSET 0
#define ETH_CSR_ETH_MAC_LOW_BYTE_WIDTH 4
#define ETH_CSR_ETH_MAC_LOW_BYTE_SIZE 4
#define ETH_CSR_ETH_MAC_LOW_BYTE_OFFSET 0x0
#define ETH_CSR_ETH_MAC_HIGH_BIT_WIDTH 24
#define ETH_CSR_ETH_MAC_HIGH_BIT_MASK 0xffffff
#define ETH_CSR_ETH_MAC_HIGH_BIT_OFFSET 0
#define ETH_CSR_ETH_MAC_HIGH_BYTE_WIDTH 4
#define ETH_CSR_ETH_MAC_HIGH_BYTE_SIZE 4
#define ETH_CSR_ETH_MAC_HIGH_BYTE_OFFSET 0x4
#define ETH_CSR_ETH_IP_BIT_WIDTH 32
#define ETH_CSR_ETH_IP_BIT_MASK 0xffffffff
#define ETH_CSR_ETH_IP_BIT_OFFSET 0
#define ETH_CSR_ETH_IP_BYTE_WIDTH 4
#define ETH_CSR_ETH_IP_BYTE_SIZE 4
#define ETH_CSR_ETH_IP_BYTE_OFFSET 0x8
#define ETH_CSR_GATEWAY_IP_BIT_WIDTH 32
#define ETH_CSR_GATEWAY_IP_BIT_MASK 0xffffffff
#define ETH_CSR_GATEWAY_IP_BIT_OFFSET 0
#define ETH_CSR_GATEWAY_IP_BYTE_WIDTH 4
#define ETH_CSR_GATEWAY_IP_BYTE_SIZE 4
#define ETH_CSR_GATEWAY_IP_BYTE_OFFSET 0xc
#define ETH_CSR_SUBNET_MASK_BIT_WIDTH 32
#define ETH_CSR_SUBNET_MASK_BIT_MASK 0xffffffff
#define ETH_CSR_SUBNET_MASK_BIT_OFFSET 0
#define ETH_CSR_SUBNET_MASK_BYTE_WIDTH 4
#define ETH_CSR_SUBNET_MASK_BYTE_SIZE 4
#define ETH_CSR_SUBNET_MASK_BYTE_OFFSET 0x10
#define ETH_CSR_RECV_MAC_LOW_BIT_WIDTH 24
#define ETH_CSR_RECV_MAC_LOW_BIT_MASK 0xffffff
#define ETH_CSR_RECV_MAC_LOW_BIT_OFFSET 0
#define ETH_CSR_RECV_MAC_LOW_BYTE_WIDTH 4
#define ETH_CSR_RECV_MAC_LOW_BYTE_SIZE 4
#define ETH_CSR_RECV_MAC_LOW_BYTE_OFFSET 0x14
#define ETH_CSR_RECV_MAC_HIGH_BIT_WIDTH 24
#define ETH_CSR_RECV_MAC_HIGH_BIT_MASK 0xffffff
#define ETH_CSR_RECV_MAC_HIGH_BIT_OFFSET 0
#define ETH_CSR_RECV_MAC_HIGH_BYTE_WIDTH 4
#define ETH_CSR_RECV_MAC_HIGH_BYTE_SIZE 4
#define ETH_CSR_RECV_MAC_HIGH_BYTE_OFFSET 0x18
#define ETH_CSR_RECV_IP_BIT_WIDTH 32
#define ETH_CSR_RECV_IP_BIT_MASK 0xffffffff
#define ETH_CSR_RECV_IP_BIT_OFFSET 0
#define ETH_CSR_RECV_IP_BYTE_WIDTH 4
#define ETH_CSR_RECV_IP_BYTE_SIZE 4
#define ETH_CSR_RECV_IP_BYTE_OFFSET 0x1c
#define ETH_CSR_RECV_UDP_LENGTH_BIT_WIDTH 16
#define ETH_CSR_RECV_UDP_LENGTH_BIT_MASK 0xffff
#define ETH_CSR_RECV_UDP_LENGTH_BIT_OFFSET 0
#define ETH_CSR_RECV_UDP_LENGTH_BYTE_WIDTH 4
#define ETH_CSR_RECV_UDP_LENGTH_BYTE_SIZE 4
#define ETH_CSR_RECV_UDP_LENGTH_BYTE_OFFSET 0x20
#define ETH_CSR_RECV_UDP_SRC_PORT_BIT_WIDTH 16
#define ETH_CSR_RECV_UDP_SRC_PORT_BIT_MASK 0xffff
#define ETH_CSR_RECV_UDP_SRC_PORT_BIT_OFFSET 0
#define ETH_CSR_RECV_UDP_SRC_PORT_BYTE_WIDTH 4
#define ETH_CSR_RECV_UDP_SRC_PORT_BYTE_SIZE 4
#define ETH_CSR_RECV_UDP_SRC_PORT_BYTE_OFFSET 0x24
#define ETH_CSR_RECV_UDP_DST_PORT_BIT_WIDTH 16
#define ETH_CSR_RECV_UDP_DST_PORT_BIT_MASK 0xffff
#define ETH_CSR_RECV_UDP_DST_PORT_BIT_OFFSET 0
#define ETH_CSR_RECV_UDP_DST_PORT_BYTE_WIDTH 4
#define ETH_CSR_RECV_UDP_DST_PORT_BYTE_SIZE 4
#define ETH_CSR_RECV_UDP_DST_PORT_BYTE_OFFSET 0x28
#define ETH_CSR_RECV_FIFO_CLEAR_BIT_WIDTH 1
#define ETH_CSR_RECV_FIFO_CLEAR_BIT_MASK 0x1
#define ETH_CSR_RECV_FIFO_CLEAR_BIT_OFFSET 0
#define ETH_CSR_RECV_FIFO_CLEAR_BYTE_WIDTH 4
#define ETH_CSR_RECV_FIFO_CLEAR_BYTE_SIZE 4
#define ETH_CSR_RECV_FIFO_CLEAR_BYTE_OFFSET 0x2c
#define ETH_CSR_RECV_FIFO_RD_PTR_BIT_WIDTH 32
#define ETH_CSR_RECV_FIFO_RD_PTR_BIT_MASK 0xffffffff
#define ETH_CSR_RECV_FIFO_RD_PTR_BIT_OFFSET 0
#define ETH_CSR_RECV_FIFO_RD_PTR_BYTE_WIDTH 4
#define ETH_CSR_RECV_FIFO_RD_PTR_BYTE_SIZE 4
#define ETH_CSR_RECV_FIFO_RD_PTR_BYTE_OFFSET 0x30
#define ETH_CSR_RECV_FIFO_WR_PTR_BIT_WIDTH 32
#define ETH_CSR_RECV_FIFO_WR_PTR_BIT_MASK 0xffffffff
#define ETH_CSR_RECV_FIFO_WR_PTR_BIT_OFFSET 0
#define ETH_CSR_RECV_FIFO_WR_PTR_BYTE_WIDTH 4
#define ETH_CSR_RECV_FIFO_WR_PTR_BYTE_SIZE 4
#define ETH_CSR_RECV_FIFO_WR_PTR_BYTE_OFFSET 0x34
#define ETH_CSR_RECV_FIFO_FULL_BIT_WIDTH 1
#define ETH_CSR_RECV_FIFO_FULL_BIT_MASK 0x1
#define ETH_CSR_RECV_FIFO_FULL_BIT_OFFSET 0
#define ETH_CSR_RECV_FIFO_FULL_BYTE_WIDTH 4
#define ETH_CSR_RECV_FIFO_FULL_BYTE_SIZE 4
#define ETH_CSR_RECV_FIFO_FULL_BYTE_OFFSET 0x38
#define ETH_CSR_RECV_FIFO_EMPTY_BIT_WIDTH 1
#define ETH_CSR_RECV_FIFO_EMPTY_BIT_MASK 0x1
#define ETH_CSR_RECV_FIFO_EMPTY_BIT_OFFSET 0
#define ETH_CSR_RECV_FIFO_EMPTY_BYTE_WIDTH 4
#define ETH_CSR_RECV_FIFO_EMPTY_BYTE_SIZE 4
#define ETH_CSR_RECV_FIFO_EMPTY_BYTE_OFFSET 0x3c
#define ETH_CSR_SEND_MAC_LOW_BIT_WIDTH 24
#define ETH_CSR_SEND_MAC_LOW_BIT_MASK 0xffffff
#define ETH_CSR_SEND_MAC_LOW_BIT_OFFSET 0
#define ETH_CSR_SEND_MAC_LOW_BYTE_WIDTH 4
#define ETH_CSR_SEND_MAC_LOW_BYTE_SIZE 4
#define ETH_CSR_SEND_MAC_LOW_BYTE_OFFSET 0x40
#define ETH_CSR_SEND_MAC_HIGH_BIT_WIDTH 24
#define ETH_CSR_SEND_MAC_HIGH_BIT_MASK 0xffffff
#define ETH_CSR_SEND_MAC_HIGH_BIT_OFFSET 0
#define ETH_CSR_SEND_MAC_HIGH_BYTE_WIDTH 4
#define ETH_CSR_SEND_MAC_HIGH_BYTE_SIZE 4
#define ETH_CSR_SEND_MAC_HIGH_BYTE_OFFSET 0x44
#define ETH_CSR_SEND_IP_BIT_WIDTH 32
#define ETH_CSR_SEND_IP_BIT_MASK 0xffffffff
#define ETH_CSR_SEND_IP_BIT_OFFSET 0
#define ETH_CSR_SEND_IP_BYTE_WIDTH 4
#define ETH_CSR_SEND_IP_BYTE_SIZE 4
#define ETH_CSR_SEND_IP_BYTE_OFFSET 0x48
#define ETH_CSR_SEND_UDP_LENGTH_BIT_WIDTH 16
#define ETH_CSR_SEND_UDP_LENGTH_BIT_MASK 0xffff
#define ETH_CSR_SEND_UDP_LENGTH_BIT_OFFSET 0
#define ETH_CSR_SEND_UDP_LENGTH_BYTE_WIDTH 4
#define ETH_CSR_SEND_UDP_LENGTH_BYTE_SIZE 4
#define ETH_CSR_SEND_UDP_LENGTH_BYTE_OFFSET 0x4c
#define ETH_CSR_SEND_SRC_PORT_BIT_WIDTH 16
#define ETH_CSR_SEND_SRC_PORT_BIT_MASK 0xffff
#define ETH_CSR_SEND_SRC_PORT_BIT_OFFSET 0
#define ETH_CSR_SEND_SRC_PORT_BYTE_WIDTH 4
#define ETH_CSR_SEND_SRC_PORT_BYTE_SIZE 4
#define ETH_CSR_SEND_SRC_PORT_BYTE_OFFSET 0x50
#define ETH_CSR_SEND_DST_PORT_BIT_WIDTH 16
#define ETH_CSR_SEND_DST_PORT_BIT_MASK 0xffff
#define ETH_CSR_SEND_DST_PORT_BIT_OFFSET 0
#define ETH_CSR_SEND_DST_PORT_BYTE_WIDTH 4
#define ETH_CSR_SEND_DST_PORT_BYTE_SIZE 4
#define ETH_CSR_SEND_DST_PORT_BYTE_OFFSET 0x54
#define ETH_CSR_SEND_FIFO_CLEAR_BIT_WIDTH 1
#define ETH_CSR_SEND_FIFO_CLEAR_BIT_MASK 0x1
#define ETH_CSR_SEND_FIFO_CLEAR_BIT_OFFSET 0
#define ETH_CSR_SEND_FIFO_CLEAR_BYTE_WIDTH 4
#define ETH_CSR_SEND_FIFO_CLEAR_BYTE_SIZE 4
#define ETH_CSR_SEND_FIFO_CLEAR_BYTE_OFFSET 0x58
#define ETH_CSR_SEND_FIFO_RD_PTR_BIT_WIDTH 32
#define ETH_CSR_SEND_FIFO_RD_PTR_BIT_MASK 0xffffffff
#define ETH_CSR_SEND_FIFO_RD_PTR_BIT_OFFSET 0
#define ETH_CSR_SEND_FIFO_RD_PTR_BYTE_WIDTH 4
#define ETH_CSR_SEND_FIFO_RD_PTR_BYTE_SIZE 4
#define ETH_CSR_SEND_FIFO_RD_PTR_BYTE_OFFSET 0x5c
#define ETH_CSR_SEND_FIFO_WR_PTR_BIT_WIDTH 32
#define ETH_CSR_SEND_FIFO_WR_PTR_BIT_MASK 0xffffffff
#define ETH_CSR_SEND_FIFO_WR_PTR_BIT_OFFSET 0
#define ETH_CSR_SEND_FIFO_WR_PTR_BYTE_WIDTH 4
#define ETH_CSR_SEND_FIFO_WR_PTR_BYTE_SIZE 4
#define ETH_CSR_SEND_FIFO_WR_PTR_BYTE_OFFSET 0x60
#define ETH_CSR_SEND_FIFO_FULL_BIT_WIDTH 1
#define ETH_CSR_SEND_FIFO_FULL_BIT_MASK 0x1
#define ETH_CSR_SEND_FIFO_FULL_BIT_OFFSET 0
#define ETH_CSR_SEND_FIFO_FULL_BYTE_WIDTH 4
#define ETH_CSR_SEND_FIFO_FULL_BYTE_SIZE 4
#define ETH_CSR_SEND_FIFO_FULL_BYTE_OFFSET 0x64
#define ETH_CSR_SEND_FIFO_EMPTY_BIT_WIDTH 1
#define ETH_CSR_SEND_FIFO_EMPTY_BIT_MASK 0x1
#define ETH_CSR_SEND_FIFO_EMPTY_BIT_OFFSET 0
#define ETH_CSR_SEND_FIFO_EMPTY_BYTE_WIDTH 4
#define ETH_CSR_SEND_FIFO_EMPTY_BYTE_SIZE 4
#define ETH_CSR_SEND_FIFO_EMPTY_BYTE_OFFSET 0x68
#define ETH_CSR_SEND_PKT_BIT_WIDTH 1
#define ETH_CSR_SEND_PKT_BIT_MASK 0x1
#define ETH_CSR_SEND_PKT_BIT_OFFSET 0
#define ETH_CSR_SEND_PKT_BYTE_WIDTH 4
#define ETH_CSR_SEND_PKT_BYTE_SIZE 4
#define ETH_CSR_SEND_PKT_BYTE_OFFSET 0x6c
#define ETH_CSR_CLEAR_IRQ_BIT_WIDTH 1
#define ETH_CSR_CLEAR_IRQ_BIT_MASK 0x1
#define ETH_CSR_CLEAR_IRQ_BIT_OFFSET 0
#define ETH_CSR_CLEAR_IRQ_BYTE_WIDTH 4
#define ETH_CSR_CLEAR_IRQ_BYTE_SIZE 4
#define ETH_CSR_CLEAR_IRQ_BYTE_OFFSET 0x70
#define ETH_CSR_CLEAR_ARP_BIT_WIDTH 1
#define ETH_CSR_CLEAR_ARP_BIT_MASK 0x1
#define ETH_CSR_CLEAR_ARP_BIT_OFFSET 0
#define ETH_CSR_CLEAR_ARP_BYTE_WIDTH 4
#define ETH_CSR_CLEAR_ARP_BYTE_SIZE 4
#define ETH_CSR_CLEAR_ARP_BYTE_OFFSET 0x74
#define ETH_CSR_IRQ_PKT_RECV_BIT_WIDTH 1
#define ETH_CSR_IRQ_PKT_RECV_BIT_MASK 0x1
#define ETH_CSR_IRQ_PKT_RECV_BIT_OFFSET 0
#define ETH_CSR_IRQ_PKT_RECV_BYTE_WIDTH 4
#define ETH_CSR_IRQ_PKT_RECV_BYTE_SIZE 4
#define ETH_CSR_IRQ_PKT_RECV_BYTE_OFFSET 0x78
#define ETH_CSR_IRQ_PKT_SENT_BIT_WIDTH 1
#define ETH_CSR_IRQ_PKT_SENT_BIT_MASK 0x1
#define ETH_CSR_IRQ_PKT_SENT_BIT_OFFSET 0
#define ETH_CSR_IRQ_PKT_SENT_BYTE_WIDTH 4
#define ETH_CSR_IRQ_PKT_SENT_BYTE_SIZE 4
#define ETH_CSR_IRQ_PKT_SENT_BYTE_OFFSET 0x7c
#define ETH_CSR_IRQ_PKT_RECV_FULL_BIT_WIDTH 1
#define ETH_CSR_IRQ_PKT_RECV_FULL_BIT_MASK 0x1
#define ETH_CSR_IRQ_PKT_RECV_FULL_BIT_OFFSET 0
#define ETH_CSR_IRQ_PKT_RECV_FULL_BYTE_WIDTH 4
#define ETH_CSR_IRQ_PKT_RECV_FULL_BYTE_SIZE 4
#define ETH_CSR_IRQ_PKT_RECV_FULL_BYTE_OFFSET 0x80
#define ETH_CSR_FILTER_EN_BIT_WIDTH 1
#define ETH_CSR_FILTER_EN_BIT_MASK 0x1
#define ETH_CSR_FILTER_EN_BIT_OFFSET 0
#define ETH_CSR_FILTER_EN_BYTE_WIDTH 4
#define ETH_CSR_FILTER_EN_BYTE_SIZE 4
#define ETH_CSR_FILTER_EN_BYTE_OFFSET 0x84
#define ETH_CSR_FILTER_PORT_BIT_WIDTH 16
#define ETH_CSR_FILTER_PORT_BIT_MASK 0xffff
#define ETH_CSR_FILTER_PORT_BIT_OFFSET 0
#define ETH_CSR_FILTER_PORT_BYTE_WIDTH 4
#define ETH_CSR_FILTER_PORT_BYTE_SIZE 4
#define ETH_CSR_FILTER_PORT_BYTE_OFFSET 0x88
#define ETH_CSR_FILTER_IP_BIT_WIDTH 32
#define ETH_CSR_FILTER_IP_BIT_MASK 0xffffffff
#define ETH_CSR_FILTER_IP_BIT_OFFSET 0
#define ETH_CSR_FILTER_IP_BYTE_WIDTH 4
#define ETH_CSR_FILTER_IP_BYTE_SIZE 4
#define ETH_CSR_FILTER_IP_BYTE_OFFSET 0x8c
typedef struct {
  uint32_t eth_mac_low;
  uint32_t eth_mac_high;
  uint32_t eth_ip;
  uint32_t gateway_ip;
  uint32_t subnet_mask;
  uint32_t recv_mac_low;
  uint32_t recv_mac_high;
  uint32_t recv_ip;
  uint32_t recv_udp_length;
  uint32_t recv_udp_src_port;
  uint32_t recv_udp_dst_port;
  uint32_t recv_fifo_clear;
  uint32_t recv_fifo_rd_ptr;
  uint32_t recv_fifo_wr_ptr;
  uint32_t recv_fifo_full;
  uint32_t recv_fifo_empty;
  uint32_t send_mac_low;
  uint32_t send_mac_high;
  uint32_t send_ip;
  uint32_t send_udp_length;
  uint32_t send_src_port;
  uint32_t send_dst_port;
  uint32_t send_fifo_clear;
  uint32_t send_fifo_rd_ptr;
  uint32_t send_fifo_wr_ptr;
  uint32_t send_fifo_full;
  uint32_t send_fifo_empty;
  uint32_t send_pkt;
  uint32_t clear_irq;
  uint32_t clear_arp;
  uint32_t irq_pkt_recv;
  uint32_t irq_pkt_sent;
  uint32_t irq_pkt_recv_full;
  uint32_t filter_en;
  uint32_t filter_port;
  uint32_t filter_ip;
  uint32_t __reserved_0x90;
  uint32_t __reserved_0x94;
  uint32_t __reserved_0x98;
  uint32_t __reserved_0x9c;
  uint32_t __reserved_0xa0;
  uint32_t __reserved_0xa4;
  uint32_t __reserved_0xa8;
  uint32_t __reserved_0xac;
  uint32_t __reserved_0xb0;
  uint32_t __reserved_0xb4;
  uint32_t __reserved_0xb8;
  uint32_t __reserved_0xbc;
  uint32_t __reserved_0xc0;
  uint32_t __reserved_0xc4;
  uint32_t __reserved_0xc8;
  uint32_t __reserved_0xcc;
  uint32_t __reserved_0xd0;
  uint32_t __reserved_0xd4;
  uint32_t __reserved_0xd8;
  uint32_t __reserved_0xdc;
  uint32_t __reserved_0xe0;
  uint32_t __reserved_0xe4;
  uint32_t __reserved_0xe8;
  uint32_t __reserved_0xec;
  uint32_t __reserved_0xf0;
  uint32_t __reserved_0xf4;
  uint32_t __reserved_0xf8;
  uint32_t __reserved_0xfc;
} eth_csr_t;
#endif
